### ISSUE TITLE
Relay toggle graphic missing

### ISSUE THREAD

**Issue by JeffyBeepBoop** [DanielBaulig/esphome-web-app#11]
2 or the 4 toggles on my esp device do not show their gui element. They were ones that were off on connection. The ones that were on on connection show the toggle. For the missing ones, I can still tap to toggle, and it shows the graphic on touch, and the disappears again. 

iOS Safari: 16.1.2

**Comment by JeffyBeepBoop** [comment]
See Inverter and relay3

![image](https://github.com/DanielBaulig/esphome-web-app/assets/79879140/da0e93e6-9236-4383-9008-cc168ab9acc3)

**Comment by DanielBaulig** [comment]
I tried reproducing the issue here with me using regular switches and I don't seem to be able to do so. If you have the ESPHome yaml for this firmware, it might be useful if you could share that with me. There might be something special about the state that these switches report. Otherwise I may need to implement and ship issue #14 first to be able get some more debugging data from you.

**Comment by DanielBaulig** [comment]
A couple more questions:
- if you reload the page, I assume the issue persists?
- if you toggle one of the switches that doesn't show and reload the page, will it then show it?
- if you toggle one of the switches that do show and reload the page, will it then not show?

**Comment by DanielBaulig** [comment]
@JeffyBeepBoop Would you mind seeing if you still run into this? I've made some change that I believe might resolve the issue.

**Comment by DanielBaulig** [comment]
Assuming fixed until I hear otherwise.
